; PlatformIO Project Configuration File
;
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 9600
lib_deps =
    madhephaestus/ESP32Servo@3.2.1
    knolleary/PubSubClient@2.8.0
    jandelgado/JLed@4.15.0
